title: MiniProject
baseurl: "/miniproject"
url: https://github.com/brk12696/miniproject
markdown: kramdown
theme: hacker
plugins:
  jekyll-relative-links
  jekyll-theme-hacker
relative_links:
  enabled: true
  collections: true
include:
  README.md
  skills.md
  index.md
  educationemployment.md
